# The URL the site will be built for
base_url = "https://strugglers.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"

title = "The Ongoing Struggle"
description = "I'll get there eventually"
author = "Andy"

generate_feeds = true
feed_filenames = ["atom.xml"]

# `zole serve` doesn't seem to like hardlinls.
#hard_link_static = true

default_language = "en"
taxonomies = [{ name = "tags", feed = true, paginate_by = 10 }]

[link_checker]
skip_anchor_prefixes = ["https://en.wikipedia.org/wiki/"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true

[extra]
copy_button = true

copyright = """
© $CURRENT_YEAR Andy Smith $SEPARATOR Unless otherwise noted,
the content in this website is available under the
[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.
"""

default_theme = "dark"

email = "YW5keS1ibG9nQHN0cnVnZ2xlcnMubmV0"

favicon = "img/favicon.ico"

footer_menu = [
    { url = "sitemap.xml", name = "sitemap", trailing_slash = false },
]

footnote_backlinks = true

full_content_in_feed = true

invert_title_order = true

menu = [
    { url = "", name = "Home" },
    { url = "posts", name = "Posts" },
    { url = "tags", name = "Tags" },
]

skin = "mint"

social_media_card = "/social_cards/default.jpg"

socials = [
    { name = "Fediverse", url = "https://social.bitfolk.com/@grifferz", icon = "mastodon" },
    { name = "YouTube", url = "https://youtube.com/@grifferz", icon = "youtube" },
    { name = "GitHub", url = "https://github.com/grifferz", icon = "github" },
]

stylesheets = ["strugglers_extras.css"]
